[project]
name = "neurovolume-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "neurovolume>=0.1.0a8",
    "nibabel>=5.3.2",
    "numpy>=1.26.4",
]
